# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

trigger:
  batch: true

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '15.14.0' 
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(npm_config_cache)
      cacheHitVar: CACHE_RESTORED
    displayName: Cache npm
  - script: npm ci
    condition: ne(variables.CACHE_RESTORED, 'true')
  - script: npm run sprint
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/public/"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId)-sprint.zip"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId)-sprint.zip'
      artifactName: 'sheaft-portal-sprint'
