# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.13.0' 
  - script: |
      npm run staging
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/public/"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId)-staging.zip"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId)-staging.zip'
      artifactName: 'sheaft-portal-staging'
  - script: |
      npm run production
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/public/"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId)-production.zip"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId)-production.zip'
      artifactName: 'sheaft-portal'
