# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

trigger:
  batch: true

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(npm_config_cache)
      cacheHitVar: CACHE_RESTORED
    displayName: Cache npm    
  - script: npm ci
    condition: ne(variables.CACHE_RESTORED, 'true')
  - task: PowerShell@2
    displayName: 'Replace Staging Config'
    inputs:
      targetType: inline
      script: Copy-Item -Path "src/configs/config.staging.js" -Destination "$(System.DefaultWorkingDirectory)/src/configs/config.js"
  - script: npm run staging
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/public/"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId)-staging.zip"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId)-staging.zip'
      artifactName: 'sheaft-portal-staging'
  - task: PowerShell@2
    displayName: 'Replace Production Config'
    inputs:
      targetType: inline
      script: Copy-Item -Path "src/configs/config.production.js" -Destination "$(System.DefaultWorkingDirectory)/src/configs/config.js"
  - script: npm run production
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/public/"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId)-production.zip"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId)-production.zip'
      artifactName: 'sheaft-portal'
